postgres:
  image: postgres:9.4
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: onion321
  ports:
    - "5432:5432"
elasticsearchdata:
  build: ./elasticsearch-data
  command: "true"
elasticsearch:
  build: ./elasticsearch
  volumes_from:
    - elasticsearchdata
  ports:
    - "9200:9200"
    - "9300:9300"
rabbitmq:
  image: rabbitmq
  ports:
      - "5672:5672"
      - "15672:15672"
fastrouter:
  build: ./fastrouter
  ports:
      - "80:80"
      # TODO: Correct?
      - "8000:8000"
memcached:
  image: memcached
  ports:
      - "11211:11211"
vault:
  image: sjourdan/vault
  ports:
    - "8201:8201"
  expose:
    - "8201"
  hostname: vault
  volumes:
    - /srv/vault
    - ./vault/config.hcl:/srv/config.hcl:ro
    - ./vault/start_vault.sh:/usr/local/bin/start_vault.sh:ro
  cap_add:
    - IPC_LOCK
  entrypoint: /usr/local/bin/start_vault.sh
